import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'HOT',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className="w-full h-screen flex justify-center">{children}</body>
    </html>
  );
}
